# Generated by Django 3.2.13 on 2022-06-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users_app', '0002_auto_20220608_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(default=123, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
