# Generated by Django 3.2.13 on 2022-06-09 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users_app', '0003_customuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Уроверь персонажа')),
                ('productivity', models.IntegerField(default=0, verbose_name='Продуктивность персонажа')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс аккаунта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
