# Generated by Django 4.0.5 on 2022-06-10 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nft_shop_app', '0001_initial'),
        ('users_app', '0004_advanceduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanceduser',
            name='nft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='nft_shop_app.nft'),
        ),
    ]
